### ISSUE TITLE
Feature request: Allow the temp-package to :use other packages.

### ISSUE THREAD

**Issue by j3pic** [phoe/safe-read#3]
The fact that `safe-read` returns only uninterned symbols makes it difficult to use. I'd like to use `safe-read` to parse some data, where certain symbols have special meanings. Ideally, I'd be able to locate those symbols in the data with something like this:

```
(eq symb 'foobar)
```

Instead, I end up having to write this:

```
(string= (symbol-name symb) "FOOBAR")
```

I ended up monkey-patching the library with this code in my project:

```
(in-package :safe-read)

(defvar *use-packages* nil)
(export '(*use-packages*))

;; Extend SAFE-READ with the ability to use symbols from
;; existing packages.

(eval-when (:compile-toplevel :load-toplevel :execute)
  (defmacro with-temp-package (&body body)
    (let* ((now (format nil "~S" (local-time:now)))
           (package-name (gensym (uiop:strcat "TEMP-PKG-" now "-")))
           (package-var (gensym)))
      `(let ((,package-var (or (find-package ',package-name)
                               (make-package ',package-name :use *use-packages*))))
         (unwind-protect (let ((*package* ,package-var)) ,@body)
           (delete-package ,package-var))))))

;; Then re-evaluate some DEFUNs so they use the modified version of the macro.
```

Then I can `:export` the symbols I want to have special meanings from a package in my project, put that package
in `*use-packages*`, and have those symbols incorporated into the result from `safe-read`.

**Comment by phoe** [comment]
> `(string= (symbol-name symb) "FOOBAR")`

Let me start with a dumb question: have you considered writing a function that will compare symbols by name? I usually do stuff like

```lisp
(defun symbol=* (s1 s2)
  (string= (symbol-name s1) (symbol-name s2)))
```

in order to avoid the hassle with comparing symbols.

Still, a custom use list sounds like a good idea, although I'd rather have it as an argument to `with-temp-package` so it can be handled per single macroexpansion instead of via a global variable. I'll gladly accept a PR that does that; we can avoid breaking backwards compatibility by doing stuff like:

```lisp
(with-temp-package
  :use-list '(:mypkg)
  ...)
```

Even if it means complicating the macro a little bit to be able to parse the arguments out from the beginning of the `&body`.

**Comment by j3pic** [comment]
I have written functions like your `symbol=*` in programs that needed to match symbols regardless of package (for example, my own Lisp implementation which needed a `loop` macro).

**Comment by j3pic** [comment]
https://github.com/phoe/safe-read/pull/4

**Comment by phoe** [comment]
Welp, #4 fixed this. Time to close!
